services:
  - type: web
    name: language-learning-server
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: PORT
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: language-learning-client
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm install -g serve && serve -s build
    envVars: [] 